apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-thejas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-thejas
  template:
    metadata:
      labels:
        app: flask-thejas
    spec:
      containers:
      - name: flask-thejas
        image: flask-thejas 
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
