apiVersion: v1
kind: Service
metadata:
  name: flask-thejas-service
spec:
  type: NodePort
  selector:
    app: flask-thejas
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      