apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-thejas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-thejas
  template:
    metadata:
      labels:
        app: flask-thejas
    spec:
      containers:
      - name: flask-thejas
        image: flask-thejas
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flask-thejas
spec:
  selector:
    app: flask-thejas
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort